[package]
name = "skylight"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
atrium-api = { version = "0.25.3", features = ["agent", "bluesky"] }
atrium-repo = "0.1.3"
atrium-xrpc-client = "0.5.14"
tokio = { version = "1.45.0", features = ["full"] }
